mongodb:
  image: mongo:7.0
  replicas: 3
  storage: 2Gi

node:
  image: prachigore19/online-backend:v4
  replicas: 2
  port: 5000

react:
  image: prachigore19/online-frontend:v4
  replicas: 2
  port: 80

mongoUri: "mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017/college?replicaSet=rs0"
