apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  SPRING_DATA_MONGODB_URI: {{ .Values.mongoUri | quote }}
  MONGO_URI: {{ .Values.mongoUri | quote }}
  PORT: {{ .Values.node.port | quote }}
