apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy

spec:
  replicas: {{ .Values.react.replicas }}

  selector:
    matchLabels:
      app: react

  template:
    metadata:
      labels:
        app: react

    spec:
      containers:
        - name: react
          image: "{{ .Values.react.image }}"

          ports:
            - containerPort: {{ .Values.react.port }}

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: nginx-config
          configMap:
            name: react-config
